src/Tk/GroupBundle/Entity/TGroup.php
<?php

namespace Tk\GroupBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * TGroup
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Tk\GroupBundle\Entity\TGroupRepository")
 */
class TGroup
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    protected $name;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     */
    protected $date;

    /**
     * @ORM\ManyToOne(targetEntity="Tk\GroupBundle\Entity\Currency", cascade={"persist"})
     */
    protected $currency;

    /**
     * @var string
     *
     * @ORM\Column(name="invitationToken", type="string", length=255)
     */
    protected $invitationToken;

    /**
     * @ORM\OneToMany(targetEntity="Tk\UserBundle\Entity\Member", mappedBy="tgroup", cascade={"persist"})
     */
    protected $members;

    /**
     * @ORM\OneToMany(targetEntity="Tk\ExpenseBundle\Entity\Expense", mappedBy="group", cascade={"persist"})
     * @ORM\OrderBy({"date" = "DESC"})
     */
    protected $expenses;

    /**
     * @ORM\OneToMany(targetEntity="Tk\ListBundle\Entity\Lists", mappedBy="group", cascade={"persist"})
     */
    protected $lists;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return TGroup
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return TGroup
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set invitationToken
     *
     * @param string $invitationToken
     * @return TGroup
     */
    public function setInvitationToken($invitationToken)
    {
        $this->invitationToken = $invitationToken;

        return $this;
    }

    /**
     * Get invitationToken
     *
     * @return string 
     */
    public function getInvitationToken()
    {
        return $this->invitationToken;
    }

    /**
     * Generate invitationToken
     *
     * @return string 
     */
    public function generateInvitationToken()
    {
        $key = '';
        $keys = array_merge(range(0, 9), range('a', 'z'));

        for ($i = 0; $i < 40; $i++) {
            $key .= $keys[array_rand($keys)];
        }

    return $key;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->members = new \Doctrine\Common\Collections\ArrayCollection();
        $this->expenses = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add expenses
     *
     * @param \Tk\ExpenseBundle\Entity\Expense $expenses
     * @return TGroup
     */
    public function addExpense(\Tk\ExpenseBundle\Entity\Expense $expenses)
    {
        $this->expenses[] = $expenses;

        return $this;
    }

    /**
     * Remove expenses
     *
     * @param \Tk\ExpenseBundle\Entity\Expense $expenses
     */
    public function removeExpense(\Tk\ExpenseBundle\Entity\Expense $expenses)
    {
        $this->expenses->removeElement($expenses);
    }

    /**
     * Get expenses
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getExpenses()
    {
        return $this->expenses;
    }

    /**
     * Get total paid
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTotalPaid()
    {
        $all_expenses = $this->expenses;

        $sum = 0;
        foreach($all_expenses as $expense){
            $sum += $expense->getAmount();
        }
        return $sum;
    }    

    /**
     * Add members
     *
     * @param \Tk\UserBundle\Entity\Member $members
     * @return TGroup
     */
    public function addMember(\Tk\UserBundle\Entity\Member $members)
    {
        $this->members[] = $members;

        return $this;
    }

    /**
     * Remove members
     *
     * @param \Tk\UserBundle\Entity\Member $members
     */
    public function removeMember(\Tk\UserBundle\Entity\Member $members)
    {
        $this->members->removeElement($members);
    }

    /**
     * Get members
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMembers()
    {
        $all_members = $this->members;
        $active_members = new \Doctrine\Common\Collections\ArrayCollection();
        foreach($all_members as $member){
            if($member->getActive() == true){
                $active_members->add($member);
            }
        }
        return $active_members;
    }

    /**
     * Get array_members
     *
     * @return array
     */
    public function getArrayMembers()
    {
        $collection_members = $this->getMembers();

        $array_members = array();
        foreach ($collection_members as $member) {
            $array_members[] = $member->getName();
        }

        return $array_members;
    }

    /**
     * Get array_balances
     *
     * @return array
     */
    public function getArrayBalances()
    {
        $collection_members = $this->getMembers();

        $array_balances = array();
        foreach ($collection_members as $member) {
            $array_balances[] = $member->getBalance();
        }

        return $array_balances;
    }

    /**
     * Set currency
     *
     * @param \Tk\GroupBundle\Entity\Currency $currency
     * @return TGroup
     */
    public function setCurrency(\Tk\GroupBundle\Entity\Currency $currency = null)
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * Get currency
     *
     * @return \Tk\GroupBundle\Entity\Currency 
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Add lists
     *
     * @param \Tk\ListBundle\Entity\Lists $lists
     * @return TGroup
     */
    public function addList(\Tk\ListBundle\Entity\Lists $lists)
    {
        $this->lists[] = $lists;

        return $this;
    }

    /**
     * Remove lists
     *
     * @param \Tk\ListBundle\Entity\Lists $lists
     */
    public function removeList(\Tk\ListBundle\Entity\Lists $lists)
    {
        $this->lists->removeElement($lists);
    }

    /**
     * Get lists
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getLists()
    {
        return $this->lists;
    }
}

src/Tk/GroupBundle/Controller/DefaultController.php
<?php

namespace Tk\GroupBundle\Controller;

use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Tk\GroupBundle\Entity\TGroup;
use Tk\GroupBundle\Form\TGroupType;
use Tk\UserBundle\Entity\Member;


class DefaultController extends Controller
{
    public function indexAction()
    {
        if(!$this->getUser()->getCurrentMember()){
            return $this->redirect($this->generateUrl('tk_user_homepage'));
        }else{
            return $this->render('TkGroupBundle:Default:settings.html.twig');
        }
    }

    public function ajaxContentAction()
    {
      return $this->render('TkGroupBundle:Default:content.html.twig');
    }

    public function switchAction($id)
    {
    	$this->changeCurrentMemberAction($id);

        $route = $this->get('request')->get('route');
        return $this->redirect($this->generateUrl($route));
    }

    public function goToAction($id)
    {
        $this->changeCurrentMemberAction($id);

        return $this->redirect($this->generateUrl('tk_group_homepage'));
    }

    public function goToExpensesAction($id)
    {
        $this->changeCurrentMemberAction($id);

        return $this->redirect($this->generateUrl('tk_expense_homepage'));
    }

    public function goToListsAction($id)
    {
        $this->changeCurrentMemberAction($id);

        return $this->redirect($this->generateUrl('tk_list_homepage'));
    }

    private function changeCurrentMemberAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $member = $em->getRepository('TkUserBundle:Member')->find($id);
        $user = $this->getUser();
        $user->setCurrentMember($member);
        $em->flush();
    }

    public function newAction()
    {
        $group = new TGroup();
        $group->setDate(new \Datetime('now'));

        $form = $this->createForm(new TGroupType(), $group);

        $request = $this->get('request');

        if ($request->isMethod('POST')) {

            $form->bind($request);

            if ($form->isValid()) {

                $em = $this->getDoctrine()->getEntityManager();

                $user = $this->getUser();
                $member = new Member();
                $member->setUser($user);
                $member->setName($user->getUsername());
                $member->setTGroup($group);
                $user->setCurrentMember($member);
                $group->setInvitationToken($group->generateInvitationToken());
                $em->persist($group);
                $em->persist($member);
                $em->flush();

                return $this->redirect($this->generateUrl('tk_group_add_members'));
            }
        }

        return $this->render('TkGroupBundle:Creation:new.html.twig', array(
            'form' => $form->createView(),
            ));        
    }

    public function editAction()
    {
        $group = $this->getUser()->getCurrentMember()->getTGroup();

        $form = $this->createForm(new TGroupType(), $group);

        $request = $this->get('request');

        if ($request->isMethod('POST')) {

            $form->bind($request);

            if ($form->isValid()) {

                $em = $this->getDoctrine()->getEntityManager();
                $em->persist($group);
                $em->flush();

                return $this->redirect($this->generateUrl('tk_group_homepage'));
            }
        }

        return $this->render('TkGroupBundle:GroupActions:edit.html.twig', array(
            'form' => $form->createView(),
            ));        
    }

    public function addMemberAction()
    {   
        $defaultData = array('name' => '', 'email' => '');
        $form = $this->createFormBuilder($defaultData)
            ->add('name', 'text')
            ->add('email', 'email', array(
                'required' => false
                ))
            ->getForm();

        $request = $this->get('request');

        if ($request->isMethod('POST')) {

            $form->bind($request);

            if ($form->isValid()) {

            $data = $form->getData();
            $member = new Member();
            $member->setName($data['name']);
            $member->setEmail($data['email']);
            $member->setInvitationToken($member->generateInvitationToken());
            $member->setTGroup($this->getUser()->getCurrentMember()->getTGroup());

            $em = $this->getDoctrine()->getEntityManager();
            $em->persist($member);
            $em->flush();

            return $this->render("TkGroupBundle:Creation:showAddedMember.html.twig", array(
                'member' => $member,
            ));
        }}

        return $this->render('TkGroupBundle:GroupActions:addMember.html.twig', array(
            'form' => $form->createView(),
            ));        
    }

    public function addMembersAction()
    {   
        $new_ids = array();
        $this->get('session')->set('new_ids', $new_ids);

        return $this->render('TkGroupBundle:Creation:addMembers.html.twig');      
    }

    public function removeMemberRequestAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $member = $em->getRepository('TkUserBundle:Member')->find($id);

        if ($this->getUser()->getCurrentMember()->getTGroup() != $member->getTGroup()){
            throw new AccessDeniedException('You are not allowed to do this');
        }else{
            $this->removeMemberAction($member, $em);
            return $this->redirect($this->generateUrl('tk_group_homepage'));
        }
    }

    private function removeMemberAction($member, $em)
    {
        if($member->getUser()){
            $member->getUser()->setCurrentMember(null);
        }
        $n = sizeof($member->getMyExpenses()) + sizeof($member->getForMeExpenses());
        if ($n == 0){
            $em->remove($member);
        }else{
            $member->setActive(false);
        }
        $em->flush();
    }

    public function closeGroupAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $group = $em->getRepository('TkGroupBundle:TGroup')->find($id);

        if ($this->getUser()->getCurrentMember()->getTGroup() != $group){
            throw new AccessDeniedException('You are not allowed to do this');
        }
        else{
            foreach($group->getMembers() as $member){
                $this->removeMemberAction($member, $em);
            }               
        }
        return $this->redirect($this->generateUrl('tk_user_homepage')); 
    }

    public function addFriendAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $friend = $em->getRepository('TkUserBundle:User')->find($id);

        $member = new Member();
        $member->setUser($friend);
        $member->setName($friend->getUsername());
        $member->setTGroup($this->getUser()->getCurrentMember()->getTGroup());
        $friend->setCurrentMember($member);

        $em->persist($member);
        $em->flush();

        $session = $this->get('session');
        $new_ids = $session->get('new_ids');
        $new_ids[] = $id;
        $session->set('new_ids', $new_ids);

        return $this->render("TkGroupBundle:Creation:showAddedMember.html.twig", array(
            'member' => $member,
        ));
    }

    public function removeAddedMemberAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $member = $em->getRepository('TkUserBundle:Member')->find($id);
        $this->removeMemberAction($member, $em);
        
        if($member->getUser()){
            $session = $this->get('session');
            $new_ids = $session->get('new_ids');
            $pos = array_search($member->getUser()->getId(), $new_ids);
            print($pos);
            unset($new_ids[$pos]);
            $session->set('new_ids', $new_ids);
        }

        return $this->redirect($this->generateUrl('tk_group_add_members')); 
    }

    public function validateMembersAction()
    {
        $user = $this->getUser();
        $group = $user->getCurrentMember()->getTGroup();
        $mailer = $this->get('mailer');

        foreach($group->getMembers() as $member){
            if(!$member->getUser() and $member->getEmail()){
                $message = \Swift_Message::newInstance();
                $message->setSubject($user.' sent you an invitation on Twinkler')
                        ->setFrom(array('jules@twinkler.co' => 'Jules from Twinkler'))
                        ->setTo($member->getEmail())
                        ->setContentType('text/html')
                        ->setBody($this->renderView(':emails:invitationEmail.email.twig', array('invited' => $member, 'member' => $user->getCurrentMember())))
                ;
                $mailer->send($message);
            }else{
            }
        }

        $repo = $this->getDoctrine()->getEntityManager()->getRepository('TkUserBundle:User');

        foreach($this->get('session')->get('new_ids') as $id){

            $u = $repo->find($id);

            $message = \Swift_Message::newInstance();
            $message->setSubject($user.' added you to a group on Twinkler')
                    ->setFrom(array('jules@twinkler.co' => 'Jules from Twinkler'))
                    ->setTo($u->getEmail())
                    ->setContentType('text/html')
                    ->setBody($this->renderView(':emails:addedToGroup.email.twig', array('user' => $u, 'member' => $user->getCurrentMember())))
            ;
            $mailer->send($message);
        }

        return $this->redirect($this->generateUrl('tk_group_homepage'));
    }

    public function sendReminderEmailAction()
    {

    }
}

src/Tk/GroupBundle/Resources/views/Default/content.html.twig
{% include 'TkGroupBundle:Default:graph.html.twig' %}

{% set group = app.user.currentMember.tgroup %}

<div class="row">
	<div class="span3  offset1">
		<div class="group-info flat-container">
			<div class="group-header flat-header" style="height: 30px; margin: 5px; width: auto">	
				<span style="display: block; height:30px; vertical-align: middle; padding-top: 2px; padding-left: 10px; padding-right: 10px">
					<h2> {{ group.name }} <i class="icon-group" style="float:right;margin-top:2px;"></i></h2>
				<span>
			</div>
		</div>
		<div id="group-edit-list" class="group-info group-edit flat-container">
			<ul>
				<li>
					<a class="edit-group-a" href="{{ path('tk_group_add_members') }}">
						<div style="width:100%; height:100%; padding-top: 10px">
							ADD A FRIEND <i class="icon-plus-sign" style="float:right; margin-right: 15px"></i> 
						</div>
					</a>
				</li>
				<li>
					<a class="edit-group-a accordion-toggle" data-toggle="collapse" href="#collapse-remove-member">						
						<div style="width:100%; height:100%; padding-top: 10px">
							<i class="icon-minus-sign" style="float:right; margin-right: 15px"></i>   
							REMOVE MEMBER
						</div>		
					</a>
				</li>
				<li>
					<a  class="edit-group-a" data-toggle="collapse" href="#collapse-close-group">	
						<div style="width:100%; height:100%; padding-top: 10px">
							<i class="icon-signout" style="float:right; margin-right: 15px"></i>   
							CLOSE GROUP
						</div>			
					</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="span7">
		<div class="group-info flat-container left-arrow">
				<div class="group-info-header">
					GROUP SETTINGS
				</div>
				<div>
					<div id="collapse-remove-member" class="accordion-body collapse">
						<div class="accordion-inner">	
							<div class="well">
							{% include 'TkGroupBundle:GroupActions:removeMembers.html.twig' %}
							</div>
						</div>
					</div>
				</div>	
				<div >
					<div id="collapse-close-group" class="accordion-body collapse">
						<div class="accordion-inner">	
							<div class="well">
								<p>Are you sure you want to close the group <b>{{ app.user.currentMember.tgroup.name }}</b> ?</p>
								<small>You will not be able to access this group anymore</small>
								<p><a href="{{ path('tk_group_close', { 'id' : app.user.currentMember.tgroup.id}) }}" class="btn btn-danger" style="margin: 20px;">Yes</a><a href="" class="btn">No</a></p>
							</div>
						</div>
					</div>
				</div>
			<div id="balance" style="text-align:center;">
				<div id="balance-slimscroll">
					<canvas id="balanceChart" height="200px"></canvas>
					<table id="chart-labels">
						<tr id="balance-row">
							{% for member in app.user.currentMember.tgroup.members %}
							<td style='width:100px; min-width:100px; color:{% if member.balance >= 0 %}#A8BD44{% else %}#F97E76{% endif %}; vertical-align:top;overflow: hidden; padding:0'>{{ member.name }}</td>	
							{% endfor %}	
						</tr>
						<tr id="member-row">
							{% for member in app.user.currentMember.tgroup.members %}
							<td style='width:100px; min-width:100px; color:{% if member.balance >= 0 %}#A8BD44{% else %}#F97E76{% endif %}; vertical-align:top;overflow: hidden; padding:0'>{{ member.balance }}{{ member.tgroup.currency.symbol }}</td>
							{% endfor %}
						</tr>
					</table>
				</div>
			</div>
			<div>
				<div id="collapse-edit-expense" class="accordion-body collapse" style="display:block;">
					<div class="accordion-inner">
						<div class="well" style="text-align: center; margin: 10px 20px;">
							<div style="display: inline-block">
								<a href="" class="btn btn-success" style="width: 85px">Via email</a>
							</div>
							<div style="display: inline-block">

							</div>
							<div style="display: inline-block">
								<a class="btn btn-primary" style="width: 85px" href="#">Via Facebook</a>
							</div>
							<div style="margin-top: 20px">
								<a class="edit-group-a accordion-toggle" data-toggle="collapse" href="#collapse-edit-expense">Hide</a>
							</div>
						</div>
					</div>
				</div>
				<div style="width:100%; height: 100%; text-align: center; margin-top: 20px; border-top: 1px solid #EFF4F6;">	
					<div class="edit-group flat-btn flat-gn flat-large">
						<a class="edit-group-a accordion-toggle edit-group-a" data-toggle="collapse" href="#collapse-edit-expense">
							<div>
								<i class="icon-envelope"></i>   
								Send a Reminder
							</div>		
						</a>	
					</div>			
				</div>
			</div>
		</div>
	</div>
</div>

src/Tk/GroupBundle/Resources/views/Default/graph.html.twig
<script>
	var balances={{ app.user.currentMember.tgroup.arrayBalances|json_encode|raw }};
</script>

src/Tk/GroupBundle/Resources/views/Default/settings.html.twig
{% extends 'TkGroupBundle::index.html.twig' %}

{% block content %}

{% include 'TkGroupBundle:Default:content.html.twig' %}

{% endblock %}